version: '3'
services:
  #  database
  postgres:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # cache-redis
  redis:
    image: 'redis'
    ports:
      - 6379:6379
